lib/bern_web/router.ex
defmodule BernWeb.Router do
  use BernWeb, :router
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ~w[html]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, html: {BernWeb.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", BernWeb, log: false do
    get "/sitemap.xml", RobotController, :sitemap
    get "/robots.txt", RobotController, :robots
    get "/rss.xml", RobotController, :rss
    get "/site.webmanifest", RobotController, :site_webmanifest
    get "/browserconfig.xml", RobotController, :browserconfig
  end

  scope "/", BernWeb do
    pipe_through :browser

    live_session :default do
      live "/", PageLive, :home
      live "/blog", BlogLive, :index, as: :blog
      live "/blog/:id", BlogLive, :show, as: :blog
      live "/projects", PageLive, :projects
    end
  end

  scope "/admin" do
    pipe_through [:browser, :check_auth]
    live_dashboard "/dashboard", metrics: BernWeb.Telemetry
  end

  def check_auth(conn, _opts) do
    with {user, pass} <- Plug.BasicAuth.parse_basic_auth(conn),
         true <- user == System.get_env("AUTH_USER", "admin"),
         true <- pass == System.get_env("AUTH_PASS", "admin") do
      conn
    else
      _ ->
        conn
        |> Plug.BasicAuth.request_basic_auth()
        |> halt()
    end
  end
end

lib/bern_web/views/layout_view.ex
defmodule BernWeb.LayoutView do
  use BernWeb, :view
  alias Phoenix.LiveView.JS

  def expand_mobile_menu do
    JS.toggle(to: "#MobileMenuContent")
    |> JS.toggle(to: "#MobileMenuIconOpen")
    |> JS.toggle(to: "#MobileMenuIconClose")
  end
end

lib/bern_web/templates/layout/_thinking_elixir_icons.html.eex
<%# _thinking_elixir_icons.html. eex template %>
<meta name="msapplication-TileColor" content="#603cba">
<meta name="theme-color" content="#ffffff">
<link rel="mask-icon" href="<%= Routes.static_path(@conn, "/images/thinking-elixir/safari-pinned-tab.svg") %>" color="#5bbad5">
<link rel="manifest" href="<%= Routes.robot_path(@conn, :site_webmanifest) %>" %>
<link rel="apple-touch-icon" type="image/png" href="<%= Routes.static_path(@conn, "/images/thinking-elixir/apple-touch-icon.png") %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= Routes.static_path(@conn, "/images/thinking-elixir/favicon-16x16.png") %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= Routes.static_path(@conn, "/images/thinking-elixir/favicon-32x32.png") %>">

lib/bern_web/templates/layout/footer.html.eex
<%# footer.html. eex template %>

<div class="border-t-4 border-brand-500">
  <div class="max-w-screen-xl mx-auto py-12 px-4 sm:px-6 md:flex md:items-center md:justify-between lg:px-8">
    <div class="flex justify-center md:order-2 print:hidden">
      <select class="dark:border-gray-800 border-gray-200 focus:ring-gray-500 focus:border-brand-500 ml-6 py-1 pl-2 pr-4 border-transparent bg-transparent text-gray-500 sm:text-sm rounded-md"
              x-data="themeChooser()"
              x-init="$watch('currentTheme', updateTheme)"
              x-model="currentTheme">
        <option disabled>Site theme</option>
        <template x-for="theme in colorThemes" :key="theme">
          <option :value="theme" x-text="theme" :selected="currentTheme === theme"></option>
        </template>
      </select>

      <%= outbound_link to: "https://twitter.com/bernheisel", title: "Twitter", class: "ml-6 text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">Twitter</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
          <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
        </svg>
      <% end %>
      <%= outbound_link to: "https://github.com/dbernheisel", title: "GitHub", class: "ml-6 text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">GitHub</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
          <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
        </svg>
      <% end %>
      <%= link to: Routes.robot_path(@conn, :rss), title: "RSS Feed", class: "ml-6 text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">RSS Feed</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
          <path d="M5 3a1 1 0 000 2c5.523 0 10 4.477 10 10a1 1 0 102 0C17 8.373 11.627 3 5 3z"></path>
          <path d="M4 9a1 1 0 011-1 7 7 0 017 7 1 1 0 11-2 0 5 5 0 00-5-5 1 1 0 01-1-1zM3 15a2 2 0 114 0 2 2 0 01-4 0z"></path>
        </svg>
      <% end %>
      <%= outbound_link to: "https://plausible.io/bernheisel.com", title: "Plausible", class: "ml-6 text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">Analytics</span>
        <svg viewBox="0 0 20 20" fill="currentColor" class="w-6 h-6">
          <path fill-rule="evenodd" d="M3 3a1 1 0 000 2v8a2 2 0 002 2h2.586l-1.293 1.293a1 1 0 101.414 1.414L10 15.414l2.293 2.293a1 1 0 001.414-1.414L12.414 15H15a2 2 0 002-2V5a1 1 0 100-2H3zm11.707 4.707a1 1 0 00-1.414-1.414L10 9.586 8.707 8.293a1 1 0 00-1.414 0l-2 2a1 1 0 101.414 1.414L8 10.414l1.293 1.293a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
        </svg>
      <% end %>
    </div>

    <div class="mt-8 md:mt-0 md:order-1">
      <p class="text-center text-base leading-6 text-gray-400">
      &copy; 2021 David Bernheisel<span class="hidden print:inline"> bernheisel.com</span>
      </p>
    </div>
  </div>
</div>

lib/bern_web/templates/layout/footer.html.heex
<div class="border-t-4 border-brand-500">
  <div class="max-w-screen-xl mx-auto py-12 px-4 sm:px-6 md:flex md:items-center md:justify-between lg:px-8">
    <div class="flex justify-center md:order-2 print:hidden">
      <select id="themeChooser" class="dark:border-gray-800 border-gray-200 focus:ring-gray-500 focus:border-brand-500 ml-6 py-1 pl-2 pr-4 border-transparent bg-transparent text-gray-500 sm:text-sm rounded-md">
        <option disabled>Site theme</option>
      </select>

      <%= outbound_link to: "https://twitter.com/bernheisel", title: "Twitter", class: "ml-6 text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">Twitter</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
          <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
        </svg>
      <% end %>
      <%= outbound_link to: "https://github.com/dbernheisel", title: "GitHub", class: "ml-6 text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">GitHub</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
          <path
            fill-rule="evenodd"
            d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
            clip-rule="evenodd"
          />
        </svg>
      <% end %>
      <%= link to: Routes.robot_path(@conn, :rss), title: "RSS Feed", class: "ml-6 text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">RSS Feed</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
          <path d="M5 3a1 1 0 000 2c5.523 0 10 4.477 10 10a1 1 0 102 0C17 8.373 11.627 3 5 3z"></path>
          <path d="M4 9a1 1 0 011-1 7 7 0 017 7 1 1 0 11-2 0 5 5 0 00-5-5 1 1 0 01-1-1zM3 15a2 2 0 114 0 2 2 0 01-4 0z"></path>
        </svg>
      <% end %>
      <%= outbound_link to: "https://plausible.io/bernheisel.com", title: "Plausible", class: "ml-6 text-gray-400 hover:text-gray-500" do %>
        <span class="sr-only">Analytics</span>
        <svg viewBox="0 0 20 20" fill="currentColor" class="w-6 h-6">
          <path
            fill-rule="evenodd"
            d="M3 3a1 1 0 000 2v8a2 2 0 002 2h2.586l-1.293 1.293a1 1 0 101.414 1.414L10 15.414l2.293 2.293a1 1 0 001.414-1.414L12.414 15H15a2 2 0 002-2V5a1 1 0 100-2H3zm11.707 4.707a1 1 0 00-1.414-1.414L10 9.586 8.707 8.293a1 1 0 00-1.414 0l-2 2a1 1 0 101.414 1.414L8 10.414l1.293 1.293a1 1 0 001.414 0l4-4z"
            clip-rule="evenodd"
          >
          </path>
        </svg>
      <% end %>
    </div>

    <div class="mt-8 md:mt-0 md:order-1">
      <p class="text-center text-base leading-6 text-gray-400">
        &copy; 2021 David Bernheisel <span class="hidden print:inline">bernheisel.com</span>
      </p>
    </div>
  </div>
</div>

lib/bern_web/templates/layout/lambda-nav.html.leex
<%# lambda-nav.html.l eex template %>
<% [route | _] = @conn.path_info %>

<nav @navigate="open = false; currentRoute = $event.detail" x-data="{currentRoute: '<%= route %>', open: false}" x-cloak class="print:hidden ">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex justify-between h-16">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">

        <!-- Mobile menu button -->
        <button @click="open = !open"
          class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-brand-100 focus:outline-none focus:bg-brand-100 focus:text-brand-500 transition duration-150 ease-in-out"
          aria-label="Main menu"
          aria-expanded="false">
          <svg :class="{'hidden': open, 'block': !open}" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>

          <svg :class="{'hidden': !open, 'block': open}" class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <!-- Desktop Menu -->
      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
        <div class="mt-2 p-1 flex-shrink-0 flex items-center rounded-lg bg-white px-4">
          <img class="h-10" src="https://thinkingelixir.com/wp-content/uploads/2019/03/thinking-elixir-logo2-110px.png" />
        </div>
        <div class="hidden sm:ml-6 sm:flex space-x-8">
          <%= outbound_link "Visit Thinking Elixir", to: "https://www.thinkingelixir.com",
            class: "inline-flex items-center px-1 pt-1 border-b-4 text-sm font-medium leading-5 focus:outline-none transition duration-150 ease-in-out border-transparent dark:text-gray-300 dark:hover:text-gray-200 text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:focus:text-gray-200 focus:text-gray-700 focus:border-gray-300",
            target: "_blank"
            %>


          <%= outbound_link "Back to Lambda Days 2021", to: "https://www.lambdadays.org/lambdadays2021",
            class: "inline-flex items-center px-1 pt-1 border-b-4 text-sm font-medium leading-5 focus:outline-none transition duration-150 ease-in-out border-transparent dark:text-gray-300 dark:hover:text-gray-200 text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:focus:text-gray-200 focus:text-gray-700 focus:border-gray-300",
            target: "_blank"
            %>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">

        <div class="ml-3 relative">
          <div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <!-- Mobile Menu -->
  <div :class="{'block': open, 'hidden': !open}" x-cloak class="sm:hidden">
    <div class="pt-2 pb-4 space-y-1 border-b-4 dark:border-brand-700 border-transparent">
      <%= outbound_link "Visit Thinking Elixir", to: "https://www.thinkingelixir.com",
        class: "block pl-3 pr-4 py-2 border-l-4 text-base font-medium focus:outline-none transition duration-150 ease-in-out",
        target: "_blank"
        %>


      <%= outbound_link "Back to Lambda Days 2021", to: "https://www.lambdadays.org/lambdadays2021",
        class: "block pl-3 pr-4 py-2 border-l-4 text-base font-medium focus:outline-none transition duration-150 ease-in-out",
        target: "_blank"
        %>
    </div>
  </div>
</nav>

lib/bern_web/templates/layout/lambda.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0, shrink-to-fit=no"/>
    <%= BernWeb.SEO.meta(@conn, view_module(@conn), assigns) %>
    <link rel="canonical" href="https://bernheisel.com<%= Phoenix.Controller.current_path(@conn) %>" />
    <link rel="preload" type="font/woff2" as="font" href="<%= Routes.static_path(@conn, "/fonts/FiraCode-VF.woff2") %>" crossorigin="anonymous" />
    <link rel="preload" type="font/woff2" as="font" href="<%= Routes.static_path(@conn, "/fonts/Inter-roman.var.woff2") %>" crossorigin="anonymous" />
    <%= render "_thinking_elixir_icons.html", assigns %>
    <%= csrf_meta_tag() %>
    <%= seo_tags(assigns) %>
    <%= live_title_tag assigns[:page_title] || "Home", suffix: " · Bernheisel" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script async defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/vendor.js") %>"></script>
    <%= if Application.get_env(:bern, :app_env) == :prod do %>
      <script async defer data-domain="bernheisel.com" src="https://plausible.bernheisel.com/js/index.js"></script>
      <link rel="dns-prefetch" href="https://plausible.bernheisel.com" />
    <% end %>
  </head>
  <body class="dark:bg-gray-900 dark:text-gray-100">
    <%= render "lambda-nav.html", assigns %>

    <div class="container mt-6 mx-auto px-4 sm:px-6 lg:px-8">
      <%= @inner_content %>
    </div>

    <%= render "footer.html", assigns |> Map.put(:who, "Thinking Elixir and David Bernheisel") |> Map.put(:twitter, "https://twitter.com/thinkingelixir") %>
  </body>
</html>

lib/bern_web/templates/layout/live.html.heex
<%= render("nav.html", assigns) %>

<div class="container max-w-7xl mt-6 mx-auto px-4 sm:px-6 lg:px-8">
  <main role="main">
    <%= @inner_content %>
  </main>
</div>

lib/bern_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0, shrink-to-fit=no" />
    <meta name="color-scheme" content="dark light" />
    <%= render("_icons.html", assigns) %>
    <%= csrf_meta_tag() %>
    <SEO.juice
      conn={@conn}
      config={BernWeb.SEO}
      item={SEO.item(@conn)}
      page_title={assigns[:page_title]}
    />
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")} />
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}>
    </script>
    <script async defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/vendor.js")}>
    </script>
    <%= if Application.get_env(:bern, :app_env) == :prod do %>
      <script defer data-exclude="/admin/*" data-domain="bernheisel.com" src="https://plausible.io/js/script.js">
      </script>
    <% end %>
    <script>
      if (localStorage.theme === "dark" || (!("theme" in localStorage) && window.matchMedia("(prefers-color-scheme: dark)").matches)) {
        document.documentElement.classList.add("dark")
        document.querySelector('meta[name="theme-color"]').setAttribute('content', 'rgb(17, 24, 39)')
      } else {
        document.documentElement.classList.remove("dark")
        document.querySelector('meta[name="theme-color"]').setAttribute('content', 'rgb(255, 255, 255)')
      }
    </script>
  </head>
  <body class="antialiased leading-tight bg-white text-gray-900 dark:bg-gray-900 dark:text-gray-100">
    <%= @inner_content %>
    <%= render("footer.html", assigns) %>
  </body>
</html>

lib/bern_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0, shrink-to-fit=no"/>
    <meta name="color-scheme" content="dark light">
    <link rel="preload" type="font/woff2" as="font" href="<%= Routes.static_path(@conn, "/fonts/FiraCode-VF.woff2") %>" crossorigin="anonymous" />
    <link rel="preload" type="font/woff2" as="font" href="<%= Routes.static_path(@conn, "/fonts/Inter-roman.var.woff2") %>" crossorigin="anonymous" />
    <%= render "_icons.html", assigns %>
    <%= csrf_meta_tag() %>
    <%= seo_tags(assigns) %>
    <%= live_title_tag assigns[:page_title] || "Home", suffix: " · Bernheisel" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script async defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/vendor.js") %>"></script>
    <%= if Application.get_env(:bern, :app_env) == :prod do %>
      <script async defer data-exclude="/admin/*" data-domain="bernheisel.com" src="https://plausible.bernheisel.com/js/plausible.exclusions.js"></script>
      <link rel="dns-prefetch" href="https://plausible.bernheisel.com" />
    <% end %>
    <script>
      if (localStorage.theme === "dark" || (!("theme" in localStorage) && window.matchMedia("(prefers-color-scheme: dark)").matches)) {
        document.documentElement.classList.add("dark")
      } else {
        document.documentElement.classList.remove("dark")
      }
    </script>
  </head>
  <body class="antialiased leading-tight bg-white text-gray-900 dark:bg-gray-900 dark:text-gray-100">
    <%= render "nav.html", assigns %>

    <div class="container mt-6 mx-auto px-4 sm:px-6 lg:px-8">
      <%= @inner_content %>
    </div>

    <%= render "footer.html", assigns %>
  </body>
</html>